Cleanup and trying to not try m3us that we know will fail

diff --git a/tools/mpv-once b/tools/mpv-once
--- a/tools/mpv-once
+++ b/tools/mpv-once
@@ -8,11 +8,13 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 start_name=$( tmux display-message -p '#W' )
 start_dir=$(pwd)
 start_time=0:45
+day=86400
 
 tmux rename-window "mpv-once" 2> /dev/null
 
 function finish {
   tmux rename-window "$start_name"
+  exit
 }
 trap finish EXIT
 
@@ -32,6 +34,7 @@ if [[ $# -gt 0 ]]; then
   done
   filter="$filter)"
 fi
+
 
 echo */* | tr ' ' '\n' > .listen_all
 touch .listen_done
@@ -57,13 +60,23 @@ for i in $(cat .listen_all .listen_done | awk ' { print $1 } ' | grep -E "$filte
         while [[ 0 ]]; do
 
           before=$( date +%s )
-          $player $player_opts \
-            --no-cache \
-            --start=$start_time --no-audio-display \
-            --start=0:45 --no-audio-display \
-            "$m3u"
-          player_exit=$?
-          listen_time=$(( $(date +%s) - $before ))
+          age=$(( $before - $(stat -c %Y "$m3u") ))
+
+          if [[ $age -lt $day ]]; then
+            $player $player_opts \
+              --no-cache \
+              --start=$start_time --no-audio-display \
+              "$m3u"
+
+            player_exit=$?
+            listen_time=$(( $(date +%s) - $before ))
+            echo "listen-time $lisen_time"
+          else
+            # If our m3u is over a day old we just
+            # assume failure
+            echo "m3u age: $(( age / day ))d"
+            player_exit=2
+          fi
 
           if [[ $player_exit == "2" ]]; then
             echo "woops, need to get a new set of urls"
@@ -71,9 +84,7 @@ for i in $(cat .listen_all .listen_done | awk ' { print $1 } ' | grep -E "$filte
               echo "This isn't going that well."
               break
             fi
-            set -x
             get_urls "$url" "$i"
-            set +x
             (( attempts ++ ))
             continue
           fi
